services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: bookshop
      POSTGRES_PASSWORD: bookshop
      POSTGRES_DB: bookshop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  kafka:
    # usa un tag stabile invece di :latest
    image: docker.io/redpandadata/redpanda:v24.1.9
    command:
      - redpanda
      - start
      - --smp 1
      - --mode dev-container
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9093,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://kafka:9093,external://localhost:9092
      - --rpc-addr 0.0.0.0:33145
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9644/v1/status/ready"]
      interval: 5s
      timeout: 3s
      retries: 30