apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: <nome_progetto_openshift>
spec:
  selector: { app: catalog-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080