---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.13.2
    app.quarkus.io/commit-id: 0852b2156e152284f904edc5e79df5cbf1b6b7d7
    app.quarkus.io/vcs-uri: https://github.com/antoniodimarino/demo_bookshop.git
    app.quarkus.io/build-timestamp: 2025-10-14 - 13:27:32 +0000
  labels:
    app.kubernetes.io/name: isbn-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: isbn-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: isbn-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.13.2
    app.quarkus.io/commit-id: 0852b2156e152284f904edc5e79df5cbf1b6b7d7
    app.quarkus.io/vcs-uri: https://github.com/antoniodimarino/demo_bookshop.git
    app.quarkus.io/build-timestamp: 2025-10-14 - 13:27:32 +0000
  labels:
    app.kubernetes.io/name: isbn-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: isbn-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: isbn-service
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.quarkus.io/quarkus-version: 3.13.2
        app.quarkus.io/commit-id: 0852b2156e152284f904edc5e79df5cbf1b6b7d7
        app.quarkus.io/vcs-uri: https://github.com/antoniodimarino/demo_bookshop.git
        app.quarkus.io/build-timestamp: 2025-10-14 - 13:27:32 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: isbn-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: isbn-service:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: isbn-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
