apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: inventory-service
  namespace: <nome_progetto_openshift>
spec:
  output:
    to:
      kind: ImageStreamTag
      name: inventory-service:latest
  source:
    type: Binary
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2