apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: antonio-dimarino-dev
spec:
  replicas: 1
  selector:
    matchLabels: { app: inventory-service }
  template:
    metadata:
      labels: { app: inventory-service }
    spec:
      containers:
      - name: inventory-service
        image: image-registry.openshift-image-registry.svc:5000/antonio-dimarino-dev/inventory-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_HTTP_PORT
          value: "8080"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: database-name
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        readinessProbe:
          httpGet: { path: "/q/health/ready", port: 8080 }
          initialDelaySeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet: { path: "/q/health/live", port: 8080 }
          initialDelaySeconds: 10
          timeoutSeconds: 3