apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: antonio-dimarino-dev
spec:
  selector: { app: inventory-service }
  ports:
  - name: http
    port: 80
    targetPort: 8080