apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.io/redpandadata/redpanda:latest
          imagePullPolicy: IfNotPresent
          args:
            - redpanda
            - start
            - --config=/var/lib/redpanda/data/redpanda.yaml
            - --smp=1
            - --overprovisioned
            - --check=false
            - --node-id=0
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://kafka:9092
            - --rpc-addr=0.0.0.0:33145
            - --advertise-rpc-addr=redpanda:33145
            - --mode=dev-container
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
      volumes:
        # ⚠️ Ephemeral: no persistence
        - name: redpanda-data
          emptyDir: {}