apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc # Nome della richiesta di volume
spec:
  accessModes:
    - ReadWriteOnce # Standard per un database
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          # FIX 1: Use the official image from your docker-compose.yml
          image: docker.io/library/postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            # FIX 2: Change env var names to match the official image
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
            - name: PGDATA
              value: /var/lib/postgresql/storage/data
          readinessProbe:
            # FIX 4: Update the probe command (use /bin/sh and new vars)
            exec:
              command: ["/bin/sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1 -p 5432"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            # FIX 5: Update the probe command
            exec:
              command: ["/bin/sh","-c","pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1 -p 5432"]
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: data
              # FIX 3: Change the mount path for the official image
              mountPath: /var/lib/postgresql/storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc