apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: user-service
  namespace: antonio-dimarino-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: user-service:latest
  source:
    type: Binary
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2