pipeline {
    agent any
    tools {

    }
    environment {
        OCP_API = 'https://api.rm3.7wse.p1.openshiftapps.com:6443'
        OCP_TOKEN_CRED = 'ocp-token'
        OCP_NS = 'antonio-dimarino-dev'
    }

    stages {
        // CHECKOUT DA GIT
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        // BUILD PARENT
        stage('Build Parent POM'){
            steps {
                dir(".") {
                    sh 'mvn -B -DskipTests -N install'
                }
            }
        }

        // BUILD COMMON

        // BUILD MICROSERVIZI

        // OPENSHIFT LOGIN
        stage('OpenShift Login') {
            steps {
                withCredentials([string(credentialsId: env.OCP_TOKEN_CRED, variable: 'TOKEN')]) {
                    sh 'oc login ' + env.OCP_API + ' --token=$TOKEN --insecure-skip-tls-verify'
                    sh 'oc project ' + env.OCP_NS
                }
            }
        }

        // BUILD IMAGE BINARY

        // DEPLOY/UPDATE
    }
}